version: "3.8"

services:
  ssh:
    image: quay.io/toolbx-images/debian-toolbox:12
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    ports:
      - target: 22
        published: 2222
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
